# Generated by Django 3.0.6 on 2020-06-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('AG', 'Água'), ('AL', 'Alimentação'), ('AG', 'Aluguel'), ('EN', 'Eneria'), ('LA', 'Lazer'), ('OU', 'Outros'), ('TE', 'Telecomunicações'), ('TR', 'Transporte')], default='OU', max_length=2)),
                ('data_pagamento', models.DateField(null=True)),
                ('data_vencimento', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('formaPagamento', models.CharField(choices=[('B', 'Boleto'), ('C', 'Crédito'), ('D', 'Débito'), ('P', 'Depósito'), ('O', 'Outros')], default='O', max_length=1)),
                ('situacao', models.CharField(choices=[('PG', 'Pago'), ('AP', 'A pagar')], default='AP', max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
