# Generated by Django 3.0.6 on 2020-06-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0002_auto_20200607_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='formaPagamento',
            field=models.CharField(choices=[('B', 'Boleto'), ('C', 'Crédito'), ('D', 'Débito'), ('M', 'Dinheiro'), ('P', 'Depósito'), ('O', 'Outros')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_expectativa',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_recebimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='formaRecebimento',
            field=models.CharField(choices=[('B', 'Boleto'), ('C', 'Crédito'), ('D', 'Débito'), ('M', 'Dinheiro'), ('P', 'Depósito'), ('O', 'Outros')], default='O', max_length=1),
        ),
    ]
