# Generated by Django 3.0.6 on 2020-06-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0003_auto_20200607_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldoInicial', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
